version: "3"

services:
  huawei-ups2000:
    image: clemon7/nut:nightly
    volumes:
      - "./conf:/etc/nut:ro"
      - "./state:/var/run/nut:rw"
    environment:
      - NUT_CONFPATH=/etc/nut
      - NUT_STATEPATH=/var/run/nut
      # - NUT_ALTPIDPATH=/var/run/nut
      - UID=1000
      - GID=1000
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    command: /nut/drivers/upsdrvctl -F -u nut -g nut start
  upsd:
    image: clemon7/nut:nightly
    volumes:
      - "./conf:/etc/nut:ro"
      - "./state:/var/run/nut:rw"
    ports:
      - "3493:3493/tcp"
    environment:
      - NUT_CONFPATH=/etc/nut
      - NUT_STATEPATH=/var/run/nut
      # - NUT_ALTPIDPATH=/var/run/nut
      - UID=1000
      - GID=1000
    command: /nut/server/upsd -F -u nut
    
networks:
  default: {}